version: "3.7"
services:
    wdavaire:
        build:
            context: .
        container_name: wdavaire
        depends_on:
            - wdavairedb
        restart: on-failure
        environment:
            - AVA_DATABASE_DATABASE=wdavaire
            - AVA_DATABASE_HOSTNAME=wdavairedb
            - AVA_DATABASE_USERNAME=wdavaire
            - AVA_DATABASE_PASSWORD=wdavaire
        volumes:
            - C:\wdavaire:/opt/wdavaire
    wdavairedb:
        container_name: wdavairedb
        image: mariadb
        restart: on-failure
        expose:
            - "3306"
        environment:
            - MYSQL_DATABASE=wdavaire
            - MYSQL_USER=wdavaire
            - MYSQL_PASSWORD=wdavaire
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
volumes:
    wdavaire:
